#!/bin/bash

source ./.env
WORKING_DIR=$COMPOSE_PROJECT_NAME
if [ -f "$WORKING_DIR/$ENV_NGINX_CONFIG_FILE" ]; then
    cp /dev/null $WORKING_DIR/$ENV_NGINX_CONFIG_FILE
    echo "Cleaning up" $ENV_NGINX_CONFIG_FILE
else 
    touch $WORKING_DIR/$ENV_NGINX_CONFIG_FILE
    echo "Creating $ENV_NGINX_CONFIG_FILE"
fi
if [ -f "$WORKING_DIR/$ENV_PHP_CONFIG_FILE" ]; then
    cp /dev/null $WORKING_DIR/$ENV_PHP_CONFIG_FILE
    echo "Cleaning up" $ENV_PHP_CONFIG_FILE
else 
    touch $WORKING_DIR/$ENV_PHP_CONFIG_FILE
    echo "Creating $ENV_PHP_CONFIG_FILE"
fi
sleep 1
echo "cleaing up $ENV_NGINX_CONFIG_FILE"
echo "
GZIP=$GZIP
KEEP_ALIVE_TIMEOUT=$KEEP_ALIVE_TIMEOUT
SENDFILE=$SENDFILE
TCP_NOPUSH=$TCP_NOPUSH
USER=$USER
WORKER_PROCESSES=$WORKER_PROCESSES
    #EVENTS
    WORKER_CONNECTIONS=$WORKER_CONNECTIONS
    #LOGGING
    LOG_FORMAT=$LOG_FORMAT
    ACCESSLOG_PATH=$ACCESSLOG_PATH
    ERRORLOG_PATH=$ERRORLOG_PATH
        ERROR_LOGLEVEL=$ERROR_LOGLEVEL
" >> $WORKING_DIR/$ENV_NGINX_CONFIG_FILE